Add common films
kanya384/java-filmorate pull request #11
Opened 2024-09-29 15:09 UTC by elbonreedZ

2024-09-29 15:30 UTC, kanya384 approved these changes

2024-09-29 16:13 UTC, kanya384 requested changes

2024-09-29 16:13 UTC, kanya384 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    private static final String GET_COMMON_FILMS = "SELECT f.id, f.title, f.description, f.release_date, f.duration, f.rating_id AS mpa_id," +
Немного неправильно работает, нам же нужно будет отсортировать все лайки к фильму по убыванию, а у тебя тут в любом случае запрос возвращает два лайка к фильму (по одному на каждого из пользователей), то есть лайки от других пользователей не считает. В постмане тест проходит, но он не покрывает этот случай

2024-09-29 16:30 UTC, kanya384 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    private static final String GET_COMMON_FILMS = "SELECT f.id, f.title, f.description, f.release_date, f.duration, f.rating_id AS mpa_id," +
```
SELECT f.id, f.title, f.description, f.release_date, f.duration, f.rating_id AS mpa_id, mpa.name AS mpa_name, g.id AS genre_id, g.name AS genre_name, count(fl.user_id) AS likes 
FROM films AS f
INNER JOIN film_likes AS fl ON fl.film_id = f.id 
LEFT JOIN mpa_rating AS mpa ON mpa.id = f.rating_id 
LEFT JOIN film_genre AS fg ON fg.film_id = f.id 
LEFT JOIN genre AS g ON g.id = fg.genre_id 
WHERE fl.FILM_ID IN (SELECT f.id AS flikes FROM FILMS AS f LEFT JOIN FILM_LIKES fl2 ON fl2.film_id = f.ID WHERE fl2.user_id IN (?, ?) GROUP BY f.ID HAVING COUNT(DISTINCT fl2.user_id) = 2)
GROUP BY f.id
ORDER BY likes DESC; 
```
Вот так будет правильнее, перепроверь пожалуйста

2024-09-30 01:34 UTC, elbonreedZ commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    private static final String GET_COMMON_FILMS = "SELECT f.id, f.title, f.description, f.release_date, f.duration, f.rating_id AS mpa_id," +
согласна

2024-09-30 04:52 UTC, kanya384 approved these changes

2024-09-30 11:54 UTC, BersenevaAV approved these changes

2024-09-30 18:13 UTC, merged