Add director
kanya384/java-filmorate pull request #13
Opened 2024-09-30 12:05 UTC by BersenevaAV

2024-09-30 18:11 UTC, kanya384 approved these changes

2024-09-30 23:07 UTC, elbonreedZ requested changes

2024-09-30 23:07 UTC, elbonreedZ commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        ArrayList<Long> filmIds = new ArrayList<>();
тут ты либо забыл про имя режиссера, либо такая функция большая для получения лишь айдишников не нужна, можно в самом фильме получить все айдишники конкантенацией

2024-10-01 03:39 UTC, kanya384 commented on src/main/resources/schema.sql
> +    film_id BIGINT REFERENCES films(id) ON DELETE CASCADE,
По поводу схемы согласен, @BersenevaAV переделай, плиз

2024-10-01 03:41 UTC, kanya384 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +            Set<Long> createdDirectorIds = new HashSet<>();
Тут вообще не согласен, запрос к БД это дорогостоящая операция, зачем лишний раз бд нагружать?

2024-10-01 04:01 UTC, kanya384 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        ArrayList<Long> filmIds = new ArrayList<>();
Посмотри прошлый вебинар с наставником, там Мария рекомендовала отдельным запросом искать

2024-10-01 06:56 UTC, elbonreedZ commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        ArrayList<Long> filmIds = new ArrayList<>();
А в чем плюсы? Это лаконичнее или это оптимизировано?

2024-10-01 07:02 UTC, elbonreedZ commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +            Set<Long> createdDirectorIds = new HashSet<>();
Потому что повторений по идее быть не должно. Например, если оставить сет, а не лист. Сделать у режиссеров equals по айди. Но и так и так повторений не будет по хорошему, ведь если интерфейс пользовательский будет то там из ограниченного списка выборка. К тому же в методе апдейт ты вроде как убрал эту проверку

2024-10-01 07:03 UTC, kanya384 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        ArrayList<Long> filmIds = new ArrayList<>();
Лаконичнее

2024-10-01 07:08 UTC, elbonreedZ commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        ArrayList<Long> filmIds = new ArrayList<>();
Не соглашусь что такая реализация выглядит лаконичнее, чем получать все в одном запросе и отрабатывать в rowmapper (и там код будет выглядеть проще намного). Но вообще можно так оставить, ведь у тебя с жанрами так же реализовано и это все менять не настаиваю

2024-10-01 08:49 UTC, kanya384 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +            Set<Long> createdDirectorIds = new HashSet<>();
Тут повторений и не будет, в методе create тут добавляются только уникальные. А в методе update сначала удаляем все что есть, потом добавляем новый список без повторов

2024-10-01 08:52 UTC, kanya384 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        ArrayList<Long> filmIds = new ArrayList<>();
Ну я думаю если Senior разработчик посоветовал так, то нет смысла придираться

2024-10-01 08:56 UTC, elbonreedZ commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        ArrayList<Long> filmIds = new ArrayList<>();
Она конкретно такую реализацию не советовала, я посмотрела. Ну, как знаешь

2024-10-01 08:58 UTC, elbonreedZ commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +            Set<Long> createdDirectorIds = new HashSet<>();
Если ты новый фильм создаешь, какой там повтор может быть если ключ это айди фильма (нового) + айди жанра? Апдейт отличается только удалением предыдущего

2024-10-01 09:57 UTC, merged